#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/CrawlMarkt.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/BezierSQLib.jar:$APPDIR/lib/mysql-connector-java-3.1.14-bin.jar:$APPDIR/lib/postgresql-9.2-1002.jdbc3.jar:$APPDIR/lib/sqlite-jdbc-3.7.2.jar:$APPDIR/lib/choreos.jar:$APPDIR/lib/support.jar:$APPDIR/lib/temboo.jar" CrawlMarkt "$@"
